# config file name
# - If you want to change it, make your own copy like <meaningful>.yaml
# - The config name will be postfixed to the neural network weight file name
# - update: separated configs
neural_net: broverette-humberto
data_collection: broverette-humberto
run_neural: broverette-humberto
